// ================= PREGNANCY WEEKLY CONTENT (shared data) =================
// محتوى أسبوعي لتطور الجنين، من الأسبوع 4 حتى الأسبوع 40 (حساب من أول يوم في آخر دورة شهرية)
// مصدر واحد يُستدعى من index.html لعرض بطاقة الحمل
// ملاحظة: معلومات عامة وتقريبية لأغراض التوعية فقط، وليست بديلاً عن متابعة الطبيبة.
const PREGNANCY_WEEKS = [
  { week:4,  size:{ar:'حبة خشخاش', en:'a poppy seed'},
       desc:{ar:'حدث الانغراس في بطانة الرحم، وبدأ هرمون الحمل (hCG) بالارتفاع — وهو نفس الهرمون الذي يكشفه اختبار الحمل المنزلي.', en:'Implantation in the uterine lining has just happened, and the pregnancy hormone (hCG) is starting to rise — the same hormone a home pregnancy test detects.'} },
  { week:5,  size:{ar:'حبة سمسم', en:'a sesame seed'},
       desc:{ar:'بدأ الأنبوب العصبي بالتشكّل، وهو أساس الدماغ والحبل الشوكي لاحقًا، كما بدأ القلب البدائي بالتكوّن.', en:'The neural tube — the future brain and spinal cord — is beginning to form, and a primitive heart is starting to take shape.'} },
  { week:6,  size:{ar:'حبة عدس', en:'a lentil'},
       desc:{ar:'قد يكون نبض القلب مرئيًا بالسونار في هذه المرحلة، وبدأت براعم صغيرة تظهر في مكان الذراعين والساقين لاحقًا.', en:'A heartbeat may already be visible on ultrasound, and tiny buds have appeared where the arms and legs will grow.'} },
  { week:7,  size:{ar:'حبة توت أزرق', en:'a blueberry'},
       desc:{ar:'الدماغ ينمو بسرعة كبيرة هذا الأسبوع، وبراعم الذراعين والساقين تطول وتتمايز أكثر.', en:'The brain is growing very quickly this week, and the arm and leg buds are lengthening and becoming more defined.'} },
  { week:8,  size:{ar:'حبة عنب صغيرة', en:'a small grape'},
       desc:{ar:'بدأت أصابع اليدين والقدمين بالتشكّل، وجميع الأعضاء الرئيسية بدأت مراحلها الأولى من التكوّن.', en:'Fingers and toes are starting to form, and all the major organs have begun their earliest stages of development.'} },
  { week:9,  size:{ar:'حبة زيتون كبيرة', en:'a large olive'},
       desc:{ar:'من الآن فصاعدًا يُسمّى "جنينًا" (fetus) بدل "مضغة"، وملامح الوجه بدأت تصبح أوضح شيئًا فشيئًا.', en:'From now on it’s called a "fetus" rather than an embryo, and facial features are gradually becoming more defined.'} },
  { week:10, size:{ar:'حبة فراولة', en:'a strawberry'},
       desc:{ar:'الأعضاء الحيوية تكوّنت وبدأت بالعمل بشكل مبدئي، وأظافر صغيرة جدًا بدأت بالظهور.', en:'The vital organs have formed and started working in a basic way, and tiny nails are beginning to appear.'} },
  { week:11, size:{ar:'حبة تين', en:'a fig'},
       desc:{ar:'الجنين بدأ يتحرك رغم أنك ما راح تحسّي فيه بعد، والعظام بدأت تتصلّب تدريجيًا.', en:'The fetus has started to move, even though you can’t feel it yet, and the bones are gradually starting to harden.'} },
  { week:12, size:{ar:'حبة ليمون صغيرة', en:'a small lime'},
       desc:{ar:'المنعكسات بدأت تتطوّر، ويقدر الجنين يفتح ويقفل أصابعه. نهاية الثلث الأول من الحمل تقريبًا.', en:'Reflexes are developing, and the fetus can open and close its fingers. This is roughly the end of the first trimester.'} },
  { week:13, size:{ar:'حبة خوخ', en:'a peach'},
       desc:{ar:'بداية الثلث الثاني تقريبًا؛ الأعضاء التناسلية الخارجية بدأت تتمايز أكثر رغم صعوبة تمييزها بالسونار بعد.', en:'Roughly the start of the second trimester; external genitalia are becoming more distinct, though usually still hard to tell apart on ultrasound.'} },
  { week:14, size:{ar:'حبة ليمون', en:'a lemon'},
       desc:{ar:'الجنين قادر على تكوين تعابير وجه بسيطة، والكليتان بدأتا بإنتاج البول.', en:'The fetus can now form simple facial expressions, and the kidneys have started producing urine.'} },
             { week:15, size:{ar:'حبة تفاح', en:'an apple'},
                       desc:{ar:'الجنين بدأ يحس بالضوء رغم أن عينيه مغمضتان، وبدأ نمط شعر فروة الرأس بالتكوّن.', en:'The fetus can now sense light even with eyes still closed, and a scalp hair pattern is starting to form.'} },
  { week:16, size:{ar:'حبة أفوكادو', en:'an avocado'},
       desc:{ar:'الهيكل العظمي يستمر بالتصلّب، وأحيانًا يمكن تحديد جنس الجنين بالسونار من هذا الأسبوع تقريبًا.', en:'The skeleton continues to harden, and it may sometimes be possible to determine the baby’s sex on ultrasound around this week.'} },
  { week:17, size:{ar:'حبة كمثرى', en:'a pear'},
       desc:{ar:'طبقات من الدهون بدأت تتكوّن تحت الجلد، والحبل السرّي أصبح أسمك وأقوى.', en:'Fat layers are beginning to form under the skin, and the umbilical cord is growing thicker and stronger.'} },
  { week:18, size:{ar:'حبة فلفل رومي', en:'a bell pepper'},
       desc:{ar:'الأذنان وصلتا موضعهما شبه النهائي، وقد يبدأ الجنين بسماع بعض الأصوات من حولك.', en:'The ears have reached close to their final position, and the fetus may begin to hear some sounds around you.'} },
  { week:19, size:{ar:'حبة طماطم كبيرة', en:'a large tomato'},
       desc:{ar:'طبقة الفيرنكس الواقية (مادة شمعية بيضاء) بدأت تغطي جلد الجنين لحمايته داخل السائل الأمنيوسي.', en:'A protective waxy coating (vernix caseosa) is starting to cover the skin, shielding it inside the amniotic fluid.'} },
  { week:20, size:{ar:'موزة', en:'a banana'},
       desc:{ar:'منتصف الحمل تقريبًا! قد تبدئين تحسّين بحركات الجنين الأولى الخفيفة ("الرفرفة").', en:'Roughly the halfway point! You may start to feel the first light flutters of movement ("quickening").'} },
  { week:21, size:{ar:'حبة جزر كبيرة', en:'a large carrot'},
       desc:{ar:'الجنين بدأ يبلع كميات صغيرة من السائل الأمنيوسي، والحواجب والجفون اكتمل تكوينها.', en:'The fetus has started swallowing small amounts of amniotic fluid, and the eyebrows and eyelids are now fully formed.'} },
  { week:22, size:{ar:'حبة باذنجان صغيرة', en:'a small eggplant'},
       desc:{ar:'حواس الجنين تستمر بالتطوّر، وقبضة يده بدأت تصبح أقوى شيئًا فشيئًا.', en:'The fetus’s senses continue developing, and its grip is gradually becoming stronger.'} },
  { week:23, size:{ar:'حبة مانجو كبيرة', en:'a large mango'},
       desc:{ar:'الأوعية الدموية في الرئتين تتطوّر استعدادًا لعملية التنفس بعد الولادة.', en:'Blood vessels in the lungs are developing in preparation for breathing after birth.'} },
  { week:24, size:{ar:'كوز ذرة', en:'an ear of corn'},
       desc:{ar:'مرحلة مهمة في تطوّر الرئتين، اللي تستمر بالنضج تدريجيًا خلال الأسابيع القادمة.', en:'An important stage for lung development, which continues to mature gradually over the coming weeks.'} },
  { week:25, size:{ar:'قرنبيط صغير', en:'a small cauliflower'},
       desc:{ar:'الجنين بدأ يكتسب مزيدًا من الدهون تحت الجلد، ويستجيب أكثر للأصوات واللمس من حوله.', en:'The fetus is gaining more fat under the skin, and responding more to sounds and touch around it.'} },
  { week:26, size:{ar:'كوسة كبيرة', en:'a large zucchini'},
       desc:{ar:'عينا الجنين بدأتا بالانفتاح تدريجيًا، والرئتان تستمران بإنتاج مادة السورفاكتانت المهمة للتنفس.', en:'The eyes are gradually starting to open, and the lungs continue producing surfactant — essential for breathing.'} },
  { week:27, size:{ar:'قرع صغير', en:'a small squash'},
       desc:{ar:'بداية الثلث الثالث والأخير من الحمل؛ أنسجة الدماغ تتطوّر بوتيرة سريعة جدًا الآن.', en:'The start of the third and final trimester; brain tissue is developing very rapidly now.'} },
  { week:28, size:{ar:'باذنجان كبير', en:'a large eggplant'},
       desc:{ar:'الجنين قادر على الرمش الآن، ودورات نوم بدائية بدأت بالتكوّن.', en:'The fetus can now blink, and basic sleep cycles are starting to form.'} },
  { week:29, size:{ar:'كوسة كبيرة جدًا', en:'a large butternut squash'},
       desc:{ar:'العضلات والرئتان يستمران بالنضج، والرأس ينمو ليستوعب الدماغ المتطوّر باستمرار.', en:'Muscles and lungs continue maturing, and the head is growing to accommodate the ever-developing brain.'} },
  { week:30, size:{ar:'ملفوف صغير', en:'a small cabbage'},
       desc:{ar:'السائل الأمنيوسي يقل نسبيًا مقارنة بحجم الجنين المتزايد، وقد يبدأ باتخاذ وضعية الرأس للأسفل.', en:'Amniotic fluid becomes relatively less compared to the baby’s growing size, and it may start settling into a head-down position.'} },
  { week:31, size:{ar:'جوز هند صغير', en:'a small coconut'},
       desc:{ar:'حركات الجنين أصبحت أكثر تناسقًا، ودخل مرحلة اكتساب وزن سريع نسبيًا.', en:'The baby’s movements are becoming more coordinated, and it has entered a phase of relatively rapid weight gain.'} },
  { week:32, size:{ar:'لفت كبير', en:'a large turnip'},
       desc:{ar:'العظام اكتمل تكوينها لكنها ما زالت طرية ومرنة، وأظافر اليدين والقدمين وصلت تقريبًا لأطراف الأصابع.', en:'The bones are fully formed but still soft and flexible, and the finger- and toenails have nearly reached the fingertips.'} },
  { week:33, size:{ar:'أناناس صغير', en:'a small pineapple'},
       desc:{ar:'الجهاز المناعي يتطوّر مع مرور أجسام مضادة من الأم عبر المشيمة، ما يمنح الجنين حماية مبكرة.', en:'The immune system is developing as antibodies pass from the mother through the placenta, giving the baby early protection.'} },
  { week:34, size:{ar:'شمام صغير', en:'a small cantaloupe'},
       desc:{ar:'أظافر الأصابع وصلت لأطراف الأصابع تقريبًا، والجهاز العصبي المركزي والرئتان ما زالا في مراحل نضج أخيرة.', en:'Fingernails have nearly reached the fingertips, while the central nervous system and lungs are still in their final stages of maturing.'} },
  { week:35, size:{ar:'قرع العسل', en:'a butternut squash'},
       desc:{ar:'معظم مراحل التطور الجسدي اكتملت تقريبًا؛ الكليتان مكتملتا النمو، والكبد بدأ معالجة بعض الفضلات.', en:'Most physical development is nearly complete; the kidneys are fully developed, and the liver has started processing some waste.'} },
  { week:36, size:{ar:'خس روماني', en:'a head of romaine lettuce'},
       desc:{ar:'قد يبدأ الجنين بالنزول أكثر نحو الحوض استعدادًا للولادة (ما يُعرف بـ"التنزّل")، واقترب من مرحلة "مبكرًا عن الأوان الكامل".', en:'The baby may start settling lower into the pelvis in preparation for birth ("lightening"), and is getting close to the "early term" stage.'} },
  { week:37, size:{ar:'سلق كبير', en:'a large bunch of chard'},
       desc:{ar:'يُعتبر الجنين الآن في مرحلة "مبكرًا عن الأوان الكامل"، ويستمر باكتساب الوزن أسبوعيًا.', en:'The baby is now considered "early term," and continues gaining weight week by week.'} },
  { week:38, size:{ar:'كراث كبير', en:'a large leek'},
       desc:{ar:'أغلب الأعضاء اكتمل نضجها واستعدت للحياة خارج الرحم، فيما يستمر الدماغ بالتطور.', en:'Most organs have finished maturing and are ready for life outside the womb, while the brain continues to develop.'} },
  { week:39, size:{ar:'بطيخ صغير', en:'a small watermelon'},
       desc:{ar:'يُعتبر الجنين الآن "مكتمل الشهور" (Full term)؛ يستمر باكتساب الوزن فيما يستمر نضج الدماغ والرئتين حتى لحظة الولادة.', en:'The baby is now considered "full term"; it continues gaining weight while the brain and lungs keep maturing right up to birth.'} },
  { week:40, size:{ar:'بطيخة متوسطة', en:'a medium watermelon'},
       desc:{ar:'موعد الولادة المتوقع! تذكّري أن أقل من 5% فقط من النساء يلدن بالضبط في التاريخ المتوقع — فولادة الجنين قبل أو بعد هذا التاريخ بأيام أمر طبيعي جدًا.', en:'Your estimated due date! Keep in mind fewer than 5% of babies are born on their exact due date — arriving a bit before or after this date is completely normal.'} },
  ];

// يرجع أقرب مُدخل في القائمة لأسبوع معيّن (نضمن عدم كسر التنقّل لو الأسبوع طلع خارج المدى 4-40)
function findPregnancyWeekEntry(week){
    const clamped = Math.max(4, Math.min(40, week));
    return PREGNANCY_WEEKS.find(w=>w.week===clamped) || PREGNANCY_WEEKS[PREGNANCY_WEEKS.length-1];
}
